version: "3.1"
services:
  api:
    image: node-backend
    restart: always
    build:
      dockerfile: Dockerfile
      context: "."
    volumes:
      - /mnt/efs/backend:/app
    env_file:
      - .env
    ports:
      - "80:5000"
